name: Create Branch with Only README

on:
  workflow_dispatch: # Memicu action secara manual

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create a new orphan branch with README only
        run: |
          # Membuat branch baru tanpa riwayat dari branch lain
          git checkout --orphan repo # Ganti 'new-branch' dengan nama branch yang diinginkan
          
          # Hapus semua file dari index
          git rm -rf .

          # Tambahkan file README.md
          echo "# Ini adalah README" > README.md
          git add README.md
          git commit -m "Add README.md only"
          
          # Push branch baru ke repository
          git push origin new-branch