name: Build and Deploy APK

on:
  push:
    branches:
      - main

env:
  EXTPATH: id/komiku  # Path ekstensi
  EXTSLUG: id-komiku  # Nama ekstensi, ini bisa dinamis

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build APK
      run: ./gradlew -p src ${{ env.EXTSLUG }}:assembleDebug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.EXTSLUG }}.zip  # Nama artefak sesuai EXTSLUG
        path: src/${{ env.EXTPATH }}/build/outputs/apk/debug/*.apk

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout target branch
      uses: actions/checkout@v4
      with:
        ref: target-branch  # Ganti dengan nama branch target Anda

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.EXTSLUG }}.zip  # Nama artefak yang diunduh sesuai EXTSLUG
        path: extracted_apk

    - name: List files in extracted_apk
      run: ls -l extracted_apk  # Verifikasi apakah file zip ada

    - name: Extract APK from ZIP
      run: |
        unzip extracted_apk/${{ env.EXTSLUG }}.zip -d extracted_apk

    - name: Copy APK to target branch
      run: |
        cp extracted_apk/*.apk .

    - name: Commit and push APK to target branch
      run: |
        git add .
        git commit -m "Add APK for ${{ github.event.inputs.lang }}-${{ github.event.inputs.extension }}"
        git push origin repo
