name: Unpack File with Manual Dispatch

on:
  workflow_dispatch:
    inputs:
      zip_file:
        description: 'Nama file zip yang akan diekstrak'
        required: true
        default: 'nama_file.zip'
      extract_to:
        description: 'Tujuan direktori ekstrak'
        required: true
        default: 'src/id/tujuan_ekstrak/'

jobs:
  unpack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install unzip (if needed)
        run: sudo apt-get install unzip -y

      - name: Unpack specified zip file to target directory
        run: unzip ${{ github.event.inputs.zip_file }} -d ${{ github.event.inputs.extract_to }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ github.event.inputs.extract_to }}
          git commit -m "Add extracted files from ${{ github.event.inputs.zip_file }}"
          git push
